// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc7NK-iycAaXGmsWKDKPv1akvbdGl4NI0',
    appId: '1:174164170830:web:5638b81e37591459998b1f',
    messagingSenderId: '174164170830',
    projectId: 'fir-authen-a584d',
    authDomain: 'fir-authen-a584d.firebaseapp.com',
    storageBucket: 'fir-authen-a584d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHG0eD6SXVz1YC1EGRSmNt3n07NMiTiNw',
    appId: '1:174164170830:android:09e447f1b56d0238998b1f',
    messagingSenderId: '174164170830',
    projectId: 'fir-authen-a584d',
    storageBucket: 'fir-authen-a584d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc7NK-iycAaXGmsWKDKPv1akvbdGl4NI0',
    appId: '1:174164170830:web:15214daf349d6204998b1f',
    messagingSenderId: '174164170830',
    projectId: 'fir-authen-a584d',
    authDomain: 'fir-authen-a584d.firebaseapp.com',
    storageBucket: 'fir-authen-a584d.firebasestorage.app',
  );
}
